name: Bahmni E2E Tests & Repository Dispatch

on: 
  push:
    barnches:
      - main
  repository_dispatch:
    types: [Smoke-Test-Dev-Lite]
  workflow_dispatch:
    inputs:
      TEST_CONTEXT:
        description: 'Test tags to be executed. eg. lite, payments, lab, hospital. Logical operators can be used.'
        required: false
        default: lite
      TEST_ENV:
        description: 'Environment to test'
        required: true
        type: choice
        default: dev.lite
        options:
          - dev.lite
          - qa.lite
          - lite
          - demo
          - demo0.9.4
env:
  TEST_CONTEXT: ${{ github.event.client_payload.TEST_CONTEXT || github.event.inputs.TEST_CONTEXT || 'lite' }}
  TEST_ENV: ${{ github.event.client_payload.TEST_ENV || github.event.inputs.TEST_ENV || 'dev.lite' }}
jobs:
  build-and-run:
    name: Build and Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - uses: zcong1993/setup-timezone@v1.1.2
        with: 
          timezone: 'Asia/Kolkata'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          sudo apt-get install -y xvfb
          sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
          sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
          sudo apt-get -y install imagemagick x11-apps
          sudo apt-get update
          sudo apt-get install -yq \
            gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
      - run: npm install @getgauge/cli
      - run: npm install
      - name: Run test
        run: xvfb-run npm run ci -- --env $TEST_ENV --tags $TEST_CONTEXT
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-e2e-reports($TEST_ENV)-${{ github.sha }}
          path: ./reports
  notification:
    name: Slack notification1
    needs:
      - build-and-run
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Success
        if: ${{ needs.build-and-run.result == 'success' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":">ðŸŸ¢ Bahmni E2E Tests Passed in $TEST_ENV. \n<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Report & Run Details #${{github.run_id}}>"}' ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Failure
        if: ${{ needs.build-and-run.result == 'failure' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"ðŸ”´ Bahmni E2E Tests Failed in $TEST_ENV. \n<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Report & Run Details #${{github.run_id}}>"}' ${{ secrets.SLACK_WEBHOOK_URL }}
